"""initial_v10_schema

Revision ID: 1060e243cb3d
Revises: None
Create Date: 2025-11-19 01:54:59.753489
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1060e243cb3d'
down_revision = None
branch_labels = None
depends_on = None




def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_key', sa.String(length=64), nullable=False),
    sa.Column('type_name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_key')
    )
    op.create_table('plan_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sessions_granted', sa.Integer(), nullable=False),
    sa.Column('cycle_period', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_offerings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('instructors',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('measurement_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_user_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['service_offerings.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('booking_permissions',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['class_templates.id'], ),
    sa.PrimaryKeyConstraint('package_id', 'template_id')
    )
    op.create_table('class_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('instructor_user_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_user_id'], ['instructors.user_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['class_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['measurement_sessions.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['measurement_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'type_id', name='uq_measurement_session_type')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_user_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', 'pending', 'suspended', name='subscription_status', native_enum=False), nullable=False),
    sa.Column('used_sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled_by_member', 'cancelled_by_admin', 'no_show', 'completed', name='booking_status', native_enum=False), server_default='confirmed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['class_events.id'], ),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_user_id', 'event_id', name='uq_booking_member_event')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payment_method', sa.Enum('NAKIT', 'KREDI_KARTI', 'HAVALE_EFT', 'DIGER', name='payment_method', native_enum=False), nullable=False),
    sa.Column('refund_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('refund_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_qr_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('qr_token', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_table('session_check_ins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('member_user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('verified_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['class_events.id'], ),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_check_ins')
    op.drop_table('subscription_qr_codes')
    op.drop_table('payments')
    op.drop_table('bookings')
    op.drop_table('subscriptions')
    op.drop_table('measurement_values')
    op.drop_table('class_events')
    op.drop_table('booking_permissions')
    op.drop_table('user_roles')
    op.drop_table('service_packages')
    op.drop_table('measurement_sessions')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('service_offerings')
    op.drop_table('service_categories')
    op.drop_table('roles')
    op.drop_table('plan_definitions')
    op.drop_table('measurement_types')
    op.drop_table('class_templates')
    # ### end Alembic commands ###