"""remove_license_table

Revision ID: 2a6a8b95f400
Revises: fef5d2dac5f8
Create Date: 2025-12-04 17:24:18.567680
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2a6a8b95f400'
down_revision = 'fef5d2dac5f8'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licenses')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('license_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('hardware_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_check_in', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('licenses_pkey')),
    sa.UniqueConstraint('license_key', name=op.f('licenses_license_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###