"""add_auto_created_class_events_to_subscription

Revision ID: b33fd22c4fa0
Revises: c2a9e8b4f1d3
Create Date: 2025-11-29 18:38:19.798709
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b33fd22c4fa0'
down_revision = 'c2a9e8b4f1d3'
branch_labels = None
depends_on = None




def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('auto_created_class_events', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'auto_created_class_events')
    # ### end Alembic commands ###