"""add_license_table

Revision ID: fef5d2dac5f8
Revises: h7i8j9k0l1m2
Create Date: 2025-12-04 16:07:42.482071
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fef5d2dac5f8'
down_revision = 'h7i8j9k0l1m2'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('license_key', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hardware_id', sa.String(length=255), nullable=True),
    sa.Column('last_check_in', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_key')
    )
    # Drop legacy timestamp columns if they exist (safe-guard for idempotent migrations)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        class_event_cols = {c['name'] for c in inspector.get_columns('class_events')}
    except Exception:
        class_event_cols = set()
    try:
        subscription_cols = {c['name'] for c in inspector.get_columns('subscriptions')}
    except Exception:
        subscription_cols = set()

    if 'created_at' in class_event_cols:
        op.drop_column('class_events', 'created_at')
    if 'updated_at' in class_event_cols:
        op.drop_column('class_events', 'updated_at')

    if 'created_at' in subscription_cols:
        op.drop_column('subscriptions', 'created_at')
    if 'updated_at' in subscription_cols:
        op.drop_column('subscriptions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('class_events', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('class_events', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table('licenses')
    # ### end Alembic commands ###